title: Linux Patching Automation
description: Enterprise-grade Linux patching automation framework
theme: jekyll-theme-architect
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - index.md
  - technical-guide.md
  - quick-start.md
  - Roadmap_09122025.md

github:
  repository_url: https://github.com/jisujit/homelab-ansible-patching
