---
- name: HomeLab Pre-Patch Assessment
  hosts: all
  gather_facts: yes
  vars:
    assessment_date: "{{ ansible_date_time.iso8601 }}"
    backup_dir: "/tmp/pre-patch-{{ ansible_date_time.epoch }}"
    
  tasks:
    - name: Create assessment directory in /tmp
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
      become: yes

    - name: Create var backups directory if not exists
      file:
        path: "/var/backups"
        state: directory
        mode: '0755'
      become: yes

    - name: Create final backup directory
      file:
        path: "/var/backups/pre-patch-{{ ansible_date_time.epoch }}"
        state: directory
        mode: '0755'
      become: yes
      register: final_backup_dir

    - name: Set backup directory variable
      set_fact:
        backup_dir: "/var/backups/pre-patch-{{ ansible_date_time.epoch }}"

    - name: Verify final backup directory exists
      stat:
        path: "{{ backup_dir }}"
      register: backup_dir_check
      become: yes

    - name: Debug backup directory status
      debug:
        msg: 
          - "Backup directory: {{ backup_dir }}"
          - "Directory exists: {{ backup_dir_check.stat.exists }}"
          - "Directory creation result: {{ final_backup_dir.changed }}"

    - name: Gather system information
      setup:
        gather_subset: all

    - name: Check available updates (Ubuntu/Debian)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_update
      when: ansible_os_family == "Debian"

    - name: List upgradable packages (Ubuntu/Debian)
      command: apt list --upgradable
      register: ubuntu_updates
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Check available updates (RHEL/CentOS)
      dnf:
        list: updates
      register: rhel_updates
      when: ansible_os_family == "RedHat"

    - name: Check disk space
      setup:
        filter: ansible_mounts
      register: disk_info

    - name: Verify minimum disk space (2GB free in /)
      assert:
        that:
          - item.size_available > 2147483648
        fail_msg: "Insufficient disk space on {{ item.mount }}"
        success_msg: "Sufficient disk space available"
      loop: "{{ ansible_mounts }}"
      when: item.mount == "/"

    - name: Check running services
      service_facts:
      register: services_before

    - name: Identify critical services
      set_fact:
        critical_services:
          - postgresql
          - mysql
          - mariadb
          - apache2
          - httpd
          - nginx
          - docker
          - kubelet
          - paperless-webserver
          - paperless-worker

    - name: Check if critical services are running
      set_fact:
        running_critical_services: "{{ services_before.ansible_facts.services.keys() | 
          intersect(critical_services) | 
          select('match', '.*\\.(service|socket)$') | 
          list }}"

    - name: Write system snapshot report
      shell: |
        cat > {{ backup_dir }}/pre_patch_report.json << 'EOL'
        {
          "hostname": "{{ inventory_hostname }}",
          "assessment_date": "{{ assessment_date }}",
          "os_info": {
            "family": "{{ ansible_os_family }}",
            "distribution": "{{ ansible_distribution }}",
            "version": "{{ ansible_distribution_version }}",
            "kernel": "{{ ansible_kernel }}"
          },
          "system_status": {
            "uptime_seconds": {{ ansible_uptime_seconds }},
            "available_updates": {{ ubuntu_updates.stdout_lines | default([]) | length if ansible_os_family == 'Debian' else rhel_updates.results | default([]) | length }},
            "running_services": {{ running_critical_services | length }}
          },
          "backup_location": "{{ backup_dir }}",
          "criticality": "{{ criticality | default('medium') }}",
          "patch_group": "{{ patch_group | default('default') }}"
        }
        EOL
      become: yes

    - name: Backup package list (Ubuntu/Debian)  
      shell: "dpkg -l > {{ backup_dir }}/installed_packages.txt"
      when: ansible_os_family == "Debian"
      become: yes

    - name: Backup critical configuration files
      shell: "cp {{ item }} {{ backup_dir }}/{{ item | basename }} || true"
      loop:
        - /etc/fstab
        - /etc/hosts
        - /etc/resolv.conf
      become: yes

    - name: Display assessment summary
      debug:
        msg:
          - "System: {{ inventory_hostname }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Updates available: {{ ubuntu_updates.stdout_lines | default([]) | length if ansible_os_family == 'Debian' else rhel_updates.results | default([]) | length }}"
          - "Critical services running: {{ running_critical_services | length }}"
          - "Backup location: {{ backup_dir }}"
